nodeLinker: "pnmp"
npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  xymox72:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${YARN_NPM_AUTH_TOKEN}"